import type { Metadata } from "next";
import "@app/globals.css";
import { Footer } from "@ui/organisms/Footer";
import { Header } from "@ui/organisms/Header";


export const metadata: Metadata = {
  title: "Home Layout",
  description: "Generated by create next app",
};

export default function AppLayout({children}: {children: React.ReactNode}) {
  return (
    <>
      <Header />
      <main className="flex-grow">
        {children}
      </main>
      <Footer />
    </>
  );
}
