import type { Metadata } from "next";
import React from 'react'

export const metadata: Metadata = {
  title: "Conditions Layout",
  description: "Generated by create next app",
};

const ConditionsLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main className='flex-grow mx-auto'>
      <article className="prose prose-lg p-6">
        {children}
      </article>
    </main>
  )
}

export default ConditionsLayout